[project]
name = "breakthrough"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "annotated-types>=0.7.0",
    "faker>=37.4.0",
    "fastapi[standard]>=0.115.13",
    "pydantic>=2.11.7",
]
